# Generated by Django 2.2.16 on 2022-03-22 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to=settings.AUTH_USER_MODEL, verbose_name='Автор рецепта'),
        ),
        migrations.AddField(
            model_name='formula',
            name='ingredients',
            field=models.ManyToManyField(to='food.AmountIngredient', verbose_name='Ингридиенты рецепта'),
        ),
        migrations.AddField(
            model_name='formula',
            name='tags',
            field=models.ManyToManyField(to='food.Tag', verbose_name='Тэги рецепта'),
        ),
        migrations.AddField(
            model_name='amountingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Ingredient', verbose_name='Название ингридиента рецепта'),
        ),
    ]
