# Generated by Django 2.2.16 on 2022-03-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20220322_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(max_length=50, verbose_name='Единицы измерения ингридиента'),
        ),
    ]
