# Generated by Django 2.2.16 on 2022-03-30 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20220328_1158'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='amountingredient',
            unique_together=set(),
        ),
    ]
