# Generated by Django 2.2.16 on 2022-03-31 12:00

from django.db import migrations, models

import food.validators


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_auto_20220331_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountingredient',
            name='amount',
            field=models.IntegerField(validators=[food.validators.validate_not_negativ_value], verbose_name='Количество ингредиента'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(validators=[food.validators.validate_not_negativ_value], verbose_name='Время приготовления рецепта'),
        ),
    ]
