# Generated by Django 2.2.16 on 2022-03-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customuser',
            name='unique_username_email',
        ),
    ]
